<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../CloudEmuera.Application/CloudEmuera.Application.csproj" />
    <ProjectReference Include="../CloudEmuera.Contracts/CloudEmuera.Contracts.csproj" />
    <ProjectReference Include="../CloudEmuera.Infrastructure/CloudEmuera.Infrastructure.csproj" />
    <ProjectReference Include="../CloudEmuera.Ipc/CloudEmuera.Ipc.csproj" />
    <ProjectReference Include="../CloudEmuera.RuntimeAdapter/CloudEmuera.RuntimeAdapter.csproj" />
    <ProjectReference Include="../CloudEmuera.Validator/CloudEmuera.Validator.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Grpc.AspNetCore" />
  </ItemGroup>
</Project>
