// <auto-generated />
using CloudEmuera.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudEmuera.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CloudEmueraDbContext))]
    [Migration("20260809190000_AddGameContentCopyLeases")]
    partial class AddGameContentCopyLeases
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.AuditEventRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_type");

                    b.Property<string>("ActorUserId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}")
                        .HasColumnName("metadata_json");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason_code");

                    b.Property<string>("RequestId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_type");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("result");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_events_occurred_at");

                    b.HasIndex("ActorUserId", "OccurredAt")
                        .HasDatabaseName("ix_audit_events_actor_time");

                    b.HasIndex("ResourceType", "ResourceId", "OccurredAt")
                        .HasDatabaseName("ix_audit_events_resource_time");

                    b.ToTable("audit_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_events_action", "length(action) BETWEEN 1 AND 128 AND instr(action, char(0)) = 0");

                            t.HasCheckConstraint("ck_audit_events_actor_type", "actor_type IN ('USER', 'ADMIN', 'SYSTEM')");

                            t.HasCheckConstraint("ck_audit_events_actor_user_id", "actor_user_id IS NULL OR (length(actor_user_id) BETWEEN 5 AND 64 AND instr(actor_user_id, char(0)) = 0)");

                            t.HasCheckConstraint("ck_audit_events_id", "substr(id, 1, 6) = 'audit_' AND length(id) BETWEEN 5 AND 64 AND instr(id, char(0)) = 0");

                            t.HasCheckConstraint("ck_audit_events_metadata_json", "length(metadata_json) BETWEEN 2 AND 1048576 AND json_valid(metadata_json) = 1 AND metadata_json <> ''");

                            t.HasCheckConstraint("ck_audit_events_occurred_at", "occurred_at >= 0");

                            t.HasCheckConstraint("ck_audit_events_reason_code", "reason_code IS NULL OR (length(reason_code) BETWEEN 1 AND 128 AND instr(reason_code, char(0)) = 0)");

                            t.HasCheckConstraint("ck_audit_events_request_id", "request_id IS NULL OR (length(request_id) BETWEEN 1 AND 128 AND instr(request_id, char(0)) = 0)");

                            t.HasCheckConstraint("ck_audit_events_resource_id", "length(resource_id) BETWEEN 1 AND 128 AND instr(resource_id, char(0)) = 0");

                            t.HasCheckConstraint("ck_audit_events_resource_type", "length(resource_type) BETWEEN 1 AND 64 AND instr(resource_type, char(0)) = 0");

                            t.HasCheckConstraint("ck_audit_events_result", "result IN ('SUCCEEDED', 'FAILED')");
                        });
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.AuthSessionRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("AbsoluteExpiresAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("absolute_expires_at");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<long>("IdleExpiresAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idle_expires_at");

                    b.Property<bool>("IsPersistent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_persistent");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("RevokeReason")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("revoke_reason");

                    b.Property<long?>("RevokedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("security_stamp");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_sessions");

                    b.HasIndex("IdleExpiresAt")
                        .HasDatabaseName("ix_auth_sessions_idle_expiry");

                    b.HasIndex("UserId", "RevokedAt", "AbsoluteExpiresAt")
                        .HasDatabaseName("ix_auth_sessions_user_active");

                    b.ToTable("auth_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_auth_sessions_id", "substr(id, 1, 6) = 'auths_' AND length(id) BETWEEN 5 AND 64 AND instr(id, char(0)) = 0");

                            t.HasCheckConstraint("ck_auth_sessions_revocation", "(revoked_at IS NULL AND revoke_reason IS NULL) OR (revoked_at IS NOT NULL AND revoke_reason IS NOT NULL AND revoked_at >= created_at)");

                            t.HasCheckConstraint("ck_auth_sessions_times", "created_at >= 0 AND created_at <= last_seen_at AND last_seen_at <= idle_expires_at AND idle_expires_at <= absolute_expires_at");
                        });
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.CloudEmueraUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("access_failed_count");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<long?>("LockoutEnd")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lockout_end");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("login_name");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("must_change_password");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(254)
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedLoginName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_login_name");

                    b.Property<long?>("PasswordChangedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("PreferencesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}")
                        .HasColumnName("preferences_json");

                    b.Property<string>("QuotaProfileId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("quota_profile_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("security_stamp");

                    b.Property<int>("StateVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("state_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email")
                        .HasFilter("normalized_email IS NOT NULL");

                    b.HasIndex("NormalizedLoginName")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_login_name");

                    b.HasIndex("QuotaProfileId")
                        .HasDatabaseName("ix_users_quota_profile");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_access_failed_count", "access_failed_count >= 0");

                            t.HasCheckConstraint("ck_users_id", "substr(id, 1, 4) = 'usr_' AND length(id) BETWEEN 5 AND 64 AND instr(id, char(0)) = 0");

                            t.HasCheckConstraint("ck_users_login_names", "length(login_name) BETWEEN 1 AND 128 AND length(normalized_login_name) BETWEEN 1 AND 128 AND instr(login_name, char(0)) = 0 AND instr(normalized_login_name, char(0)) = 0");

                            t.HasCheckConstraint("ck_users_preferences_json", "length(preferences_json) BETWEEN 2 AND 1048576 AND json_valid(preferences_json) = 1 AND preferences_json <> ''");

                            t.HasCheckConstraint("ck_users_role", "role IN ('PLAYER', 'ADMIN')");

                            t.HasCheckConstraint("ck_users_state_version", "state_version >= 0");

                            t.HasCheckConstraint("ck_users_status", "status IN ('ACTIVE', 'DISABLED')");

                            t.HasCheckConstraint("ck_users_string_lengths", "(password_hash IS NULL OR length(password_hash) BETWEEN 1 AND 512) AND length(security_stamp) BETWEEN 1 AND 128 AND instr(security_stamp, char(0)) = 0");

                            t.HasCheckConstraint("ck_users_time_order", "created_at >= 0 AND updated_at >= created_at AND (lockout_end IS NULL OR lockout_end >= 0)");
                        });
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.CompatibilityDiagnosticRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("ActivationBlocking")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activation_blocking");

                    b.Property<string>("ArgumentsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}")
                        .HasColumnName("arguments_json");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("game_id");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("line_number");

                    b.Property<string>("LogicalPath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("logical_path");

                    b.Property<string>("MessageKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("message_key");

                    b.Property<long?>("OverriddenAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("overridden_at");

                    b.Property<string>("OverriddenBy")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("overridden_by");

                    b.Property<string>("OverridePolicy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("override_policy");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("severity");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("stage");

                    b.Property<int>("WorkspaceRevision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("workspace_revision");

                    b.HasKey("Id")
                        .HasName("pk_compatibility_diagnostics");

                    b.HasIndex("OverriddenBy");

                    b.HasIndex("GameId", "WorkspaceRevision", "ActivationBlocking")
                        .HasDatabaseName("ix_compatibility_diagnostics_game_revision");

                    b.ToTable("compatibility_diagnostics", null, t =>
                        {
                            t.HasCheckConstraint("ck_compatibility_diagnostics_arguments", "length(arguments_json) BETWEEN 2 AND 1048576 AND json_valid(arguments_json) = 1 AND arguments_json <> ''");

                            t.HasCheckConstraint("ck_compatibility_diagnostics_blocking", "activation_blocking IN (0, 1)");

                            t.HasCheckConstraint("ck_compatibility_diagnostics_code", "length(code) BETWEEN 1 AND 128 AND instr(code, char(0)) = 0");

                            t.HasCheckConstraint("ck_compatibility_diagnostics_created", "created_at >= 0");

                            t.HasCheckConstraint("ck_compatibility_diagnostics_game_id", "substr(game_id, 1, 5) = 'game_' AND length(game_id) BETWEEN 5 AND 64 AND instr(game_id, char(0)) = 0");

                            t.HasCheckConstraint("ck_compatibility_diagnostics_id", "substr(id, 1, 5) = 'diag_' AND length(id) BETWEEN 5 AND 64 AND instr(id, char(0)) = 0");

                            t.HasCheckConstraint("ck_compatibility_diagnostics_line", "line_number IS NULL OR line_number > 0");

                            t.HasCheckConstraint("ck_compatibility_diagnostics_message", "length(message_key) BETWEEN 1 AND 256 AND instr(message_key, char(0)) = 0");

                            t.HasCheckConstraint("ck_compatibility_diagnostics_override", "override_policy IN ('NEVER', 'ADMIN') AND ((overridden_by IS NULL AND overridden_at IS NULL) OR (override_policy = 'ADMIN' AND overridden_by IS NOT NULL AND overridden_at IS NOT NULL))");

                            t.HasCheckConstraint("ck_compatibility_diagnostics_path", "logical_path IS NULL OR (length(logical_path) BETWEEN 1 AND 512 AND substr(logical_path, 1, 1) <> '/' AND instr(logical_path, char(92)) = 0 AND instr(logical_path, char(0)) = 0 AND instr(logical_path, '//') = 0 AND instr('/' || logical_path || '/', '/./') = 0 AND instr('/' || logical_path || '/', '/../') = 0)");

                            t.HasCheckConstraint("ck_compatibility_diagnostics_revision", "workspace_revision >= 0");

                            t.HasCheckConstraint("ck_compatibility_diagnostics_severity", "severity IN ('INFO', 'WARNING', 'ERROR')");

                            t.HasCheckConstraint("ck_compatibility_diagnostics_stage", "length(stage) BETWEEN 1 AND 32 AND instr(stage, char(0)) = 0");
                        });
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.GameContentCopyLeaseRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ConsumerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("consumer_id");

                    b.Property<string>("ConsumerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("consumer_type");

                    b.Property<string>("ContentDigest")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_digest");

                    b.Property<long>("ContentRevision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("content_revision");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expires_at");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("game_id");

                    b.HasKey("Id")
                        .HasName("pk_game_content_copy_leases");

                    b.HasIndex("ConsumerType", "ConsumerId")
                        .IsUnique()
                        .HasDatabaseName("ux_game_content_copy_leases_consumer");

                    b.HasIndex("GameId", "ContentRevision", "ExpiresAt")
                        .HasDatabaseName("ix_game_content_copy_leases_content");

                    b.ToTable("game_content_copy_leases", null, t =>
                        {
                            t.HasCheckConstraint("ck_game_content_copy_leases_consumer", "consumer_type IN ('SESSION_CREATE', 'VALIDATION') AND length(consumer_id) BETWEEN 1 AND 64 AND instr(consumer_id, char(0)) = 0");

                            t.HasCheckConstraint("ck_game_content_copy_leases_digest", "length(content_digest) = 71 AND substr(content_digest, 1, 7) = 'sha256:' AND lower(content_digest) = content_digest AND substr(content_digest, 8) NOT GLOB '*[^0-9a-f]*' AND length(substr(content_digest, 8)) = 64");

                            t.HasCheckConstraint("ck_game_content_copy_leases_game_id", "substr(game_id, 1, 5) = 'game_' AND length(game_id) BETWEEN 5 AND 64 AND instr(game_id, char(0)) = 0");

                            t.HasCheckConstraint("ck_game_content_copy_leases_id", "substr(id, 1, 4) = 'gcl_' AND length(id) BETWEEN 5 AND 64 AND instr(id, char(0)) = 0");

                            t.HasCheckConstraint("ck_game_content_copy_leases_revision", "content_revision > 0");

                            t.HasCheckConstraint("ck_game_content_copy_leases_time", "created_at >= 0 AND expires_at > created_at");
                        });
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.GameContentOperationRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at");

                    b.Property<string>("ContentDigest")
                        .HasMaxLength(71)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_digest");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_code");

                    b.Property<long>("ExpectedContentRevision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expected_content_revision");

                    b.Property<int>("ExpectedGameStateVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expected_game_state_version");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("game_id");

                    b.Property<string>("IngestionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("ingestion_id");

                    b.Property<long>("LeaseExpiresAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("operation_type");

                    b.Property<int>("StateVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("state_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkPath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("work_path");

                    b.HasKey("Id")
                        .HasName("pk_game_content_operations");

                    b.HasIndex("GameId")
                        .IsUnique()
                        .HasDatabaseName("ux_game_content_operations_active_game")
                        .HasFilter("status IN ('PENDING', 'RUNNING', 'CONTENT_READY')");

                    b.HasIndex("IngestionId")
                        .IsUnique()
                        .HasDatabaseName("ux_game_content_operations_ingestion")
                        .HasFilter("ingestion_id IS NOT NULL");

                    b.HasIndex("GameId", "CreatedAt")
                        .HasDatabaseName("ix_game_content_operations_game_created");

                    b.ToTable("game_content_operations", null, t =>
                        {
                            t.HasCheckConstraint("ck_game_content_operations_completion", "(status IN ('COMMITTED', 'FAILED') AND completed_at IS NOT NULL) OR (status NOT IN ('COMMITTED', 'FAILED') AND completed_at IS NULL)");

                            t.HasCheckConstraint("ck_game_content_operations_digest", "content_digest IS NULL OR (length(content_digest) = 71 AND substr(content_digest, 1, 7) = 'sha256:' AND lower(content_digest) = content_digest AND substr(content_digest, 8) NOT GLOB '*[^0-9a-f]*' AND length(substr(content_digest, 8)) = 64)");

                            t.HasCheckConstraint("ck_game_content_operations_error", "error_code IS NULL OR (length(error_code) BETWEEN 1 AND 128 AND instr(error_code, char(0)) = 0)");

                            t.HasCheckConstraint("ck_game_content_operations_game_id", "substr(game_id, 1, 5) = 'game_' AND length(game_id) BETWEEN 5 AND 64 AND instr(game_id, char(0)) = 0");

                            t.HasCheckConstraint("ck_game_content_operations_id", "substr(id, 1, 4) = 'gop_' AND length(id) BETWEEN 5 AND 64 AND instr(id, char(0)) = 0");

                            t.HasCheckConstraint("ck_game_content_operations_status", "status IN ('PENDING', 'RUNNING', 'CONTENT_READY', 'COMMITTED', 'FAILED')");

                            t.HasCheckConstraint("ck_game_content_operations_time", "created_at >= 0 AND updated_at >= created_at AND lease_expires_at >= created_at AND (completed_at IS NULL OR completed_at >= created_at)");

                            t.HasCheckConstraint("ck_game_content_operations_type", "operation_type IN ('IMPORT', 'RESET_WORKSPACE', 'VALIDATE', 'ACTIVATE')");

                            t.HasCheckConstraint("ck_game_content_operations_versions", "expected_game_state_version >= 0 AND expected_content_revision >= 0 AND state_version >= 0");

                            t.HasCheckConstraint("ck_game_content_operations_work_path", "work_path IS NULL OR (length(work_path) BETWEEN 1 AND 512 AND substr(work_path, 1, 1) <> '/' AND instr(work_path, char(92)) = 0 AND instr(work_path, char(0)) = 0 AND instr(work_path, '//') = 0 AND instr('/' || work_path || '/', '/./') = 0 AND instr('/' || work_path || '/', '/../') = 0)");
                        });
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.GameFileRow", b =>
                {
                    b.Property<string>("GameId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("game_id");

                    b.Property<string>("Scope")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("scope");

                    b.Property<string>("LogicalPath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("logical_path");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER")
                        .HasColumnName("byte_length");

                    b.Property<string>("ContentDigest")
                        .HasMaxLength(71)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_digest");

                    b.Property<string>("EntryKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_kind");

                    b.Property<string>("FileKind")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_kind");

                    b.Property<bool?>("HasBom")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_bom");

                    b.Property<string>("TextEncoding")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("text_encoding");

                    b.HasKey("GameId", "Scope", "LogicalPath")
                        .HasName("pk_game_files");

                    b.HasIndex("GameId", "Scope", "EntryKind")
                        .HasDatabaseName("ix_game_files_scope_kind");

                    b.ToTable("game_files", null, t =>
                        {
                            t.HasCheckConstraint("ck_game_files_digest", "(entry_kind = 'DIRECTORY' AND content_digest IS NULL) OR (entry_kind = 'FILE' AND length(content_digest) = 71 AND substr(content_digest, 1, 7) = 'sha256:' AND lower(content_digest) = content_digest AND substr(content_digest, 8) NOT GLOB '*[^0-9a-f]*' AND length(substr(content_digest, 8)) = 64)");

                            t.HasCheckConstraint("ck_game_files_file_metadata", "(entry_kind = 'DIRECTORY' AND file_kind IS NULL AND text_encoding IS NULL AND has_bom IS NULL) OR (entry_kind = 'FILE' AND file_kind IN ('TEXT', 'BINARY') AND ((file_kind = 'BINARY' AND text_encoding IS NULL AND has_bom IS NULL) OR (file_kind = 'TEXT' AND text_encoding IN ('UTF8', 'UTF8_BOM', 'SHIFT_JIS', 'UNKNOWN') AND has_bom IN (0, 1))))");

                            t.HasCheckConstraint("ck_game_files_game_id", "substr(game_id, 1, 5) = 'game_' AND length(game_id) BETWEEN 5 AND 64 AND instr(game_id, char(0)) = 0");

                            t.HasCheckConstraint("ck_game_files_kind", "entry_kind IN ('FILE', 'DIRECTORY')");

                            t.HasCheckConstraint("ck_game_files_length", "byte_length >= 0 AND (entry_kind = 'FILE' OR byte_length = 0)");

                            t.HasCheckConstraint("ck_game_files_path", "length(logical_path) BETWEEN 1 AND 512 AND substr(logical_path, 1, 1) <> '/' AND instr(logical_path, char(92)) = 0 AND instr(logical_path, char(0)) = 0 AND instr(logical_path, '//') = 0 AND instr('/' || logical_path || '/', '/./') = 0 AND instr('/' || logical_path || '/', '/../') = 0");

                            t.HasCheckConstraint("ck_game_files_scope", "scope IN ('WORKSPACE', 'CURRENT')");
                        });
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.GamePackageIngestionRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("ArchiveBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("archive_bytes");

                    b.Property<string>("ArchiveDigest")
                        .HasMaxLength(71)
                        .HasColumnType("TEXT")
                        .HasColumnName("archive_digest");

                    b.Property<long?>("CleanupCompletedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cleanup_completed_at");

                    b.Property<string>("ContentDigest")
                        .HasMaxLength(71)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_digest");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<int>("EntryCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("entry_count");

                    b.Property<long>("ExpandedBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expanded_bytes");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expires_at");

                    b.Property<string>("LimitsJson")
                        .IsRequired()
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT")
                        .HasColumnName("limits_json");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_user_id");

                    b.Property<long?>("ReservationReleasedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reservation_released_at");

                    b.Property<long>("ReservedBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reserved_bytes");

                    b.Property<string>("StagingPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("staging_path");

                    b.Property<int>("StateVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("state_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("SummaryJson")
                        .IsRequired()
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT")
                        .HasColumnName("summary_json");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_game_package_ingestions");

                    b.HasIndex("StagingPath")
                        .IsUnique()
                        .HasDatabaseName("ux_game_package_ingestions_staging_path");

                    b.HasIndex("OwnerUserId", "CreatedAt")
                        .HasDatabaseName("ix_game_package_ingestions_owner_created");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_game_package_ingestions_status_expiry");

                    b.ToTable("game_package_ingestions", null, t =>
                        {
                            t.HasCheckConstraint("ck_game_package_ingestions_archive_digest", "archive_digest IS NULL OR (length(archive_digest) = 71 AND substr(archive_digest, 1, 7) = 'sha256:' AND lower(archive_digest) = archive_digest AND substr(archive_digest, 8) NOT GLOB '*[^0-9a-f]*' AND length(substr(archive_digest, 8)) = 64)");

                            t.HasCheckConstraint("ck_game_package_ingestions_content_digest", "content_digest IS NULL OR (length(content_digest) = 71 AND substr(content_digest, 1, 7) = 'sha256:' AND lower(content_digest) = content_digest AND substr(content_digest, 8) NOT GLOB '*[^0-9a-f]*' AND length(substr(content_digest, 8)) = 64)");

                            t.HasCheckConstraint("ck_game_package_ingestions_counters", "reserved_bytes >= 0 AND archive_bytes >= 0 AND expanded_bytes >= 0 AND entry_count >= 0 AND state_version >= 0");

                            t.HasCheckConstraint("ck_game_package_ingestions_id", "substr(id, 1, 4) = 'ing_' AND length(id) BETWEEN 5 AND 64 AND instr(id, char(0)) = 0");

                            t.HasCheckConstraint("ck_game_package_ingestions_limits_json", "length(limits_json) BETWEEN 2 AND 1048576 AND json_valid(limits_json) = 1 AND limits_json <> ''");

                            t.HasCheckConstraint("ck_game_package_ingestions_owner", "substr(owner_user_id, 1, 4) = 'usr_' AND length(owner_user_id) BETWEEN 5 AND 64 AND instr(owner_user_id, char(0)) = 0");

                            t.HasCheckConstraint("ck_game_package_ingestions_path", "length(staging_path) BETWEEN 1 AND 512 AND substr(staging_path, 1, 1) <> '/' AND instr(staging_path, char(92)) = 0 AND instr(staging_path, char(0)) = 0 AND instr(staging_path, '//') = 0 AND instr('/' || staging_path || '/', '/./') = 0 AND instr('/' || staging_path || '/', '/../') = 0");

                            t.HasCheckConstraint("ck_game_package_ingestions_release", "(reserved_bytes > 0 AND reservation_released_at IS NULL) OR (reserved_bytes = 0 AND reservation_released_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_game_package_ingestions_status", "status IN ('RESERVED','RECEIVING','INSPECTING','EXTRACTING','ANALYZING','READY','CONSUMING','CONSUMED','FAILED','ABANDONED')");

                            t.HasCheckConstraint("ck_game_package_ingestions_summary_json", "length(summary_json) BETWEEN 2 AND 1048576 AND json_valid(summary_json) = 1 AND summary_json <> ''");

                            t.HasCheckConstraint("ck_game_package_ingestions_times", "created_at >= 0 AND updated_at >= created_at AND expires_at >= created_at AND (reservation_released_at IS NULL OR reservation_released_at >= created_at) AND (cleanup_completed_at IS NULL OR cleanup_completed_at >= created_at)");
                        });
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.GameRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long?>("ActivatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activated_at");

                    b.Property<string>("ActivatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("activated_by");

                    b.Property<string>("CompatibilitySummaryJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}")
                        .HasColumnName("compatibility_summary_json");

                    b.Property<string>("ContentDigest")
                        .HasMaxLength(71)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_digest");

                    b.Property<long>("ContentRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("content_revision");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentContentPath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("current_content_path");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_by");

                    b.Property<string>("ManifestJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}")
                        .HasColumnName("manifest_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("RuntimeConfigJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}")
                        .HasColumnName("runtime_config_json");

                    b.Property<int>("StateVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("state_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("visibility");

                    b.Property<string>("WorkspacePath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("workspace_path");

                    b.Property<string>("WorkspaceStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("workspace_status");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.HasIndex("ActivatedBy");

                    b.HasIndex("CurrentContentPath")
                        .IsUnique()
                        .HasDatabaseName("ux_games_current_content_path");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("WorkspacePath")
                        .IsUnique()
                        .HasDatabaseName("ux_games_workspace_path");

                    b.HasIndex("OwnerUserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_games_owner_name");

                    b.ToTable("games", null, t =>
                        {
                            t.HasCheckConstraint("ck_games_compatibility_json", "length(compatibility_summary_json) BETWEEN 2 AND 1048576 AND json_valid(compatibility_summary_json) = 1 AND compatibility_summary_json <> ''");

                            t.HasCheckConstraint("ck_games_content", "(current_content_path IS NULL AND content_digest IS NULL AND content_revision = 0 AND activated_by IS NULL AND activated_at IS NULL) OR (current_content_path IS NOT NULL AND length(content_digest) = 71 AND substr(content_digest, 1, 7) = 'sha256:' AND lower(content_digest) = content_digest AND substr(content_digest, 8) NOT GLOB '*[^0-9a-f]*' AND length(substr(content_digest, 8)) = 64 AND content_revision > 0 AND activated_by IS NOT NULL AND activated_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_games_content_path", "current_content_path IS NULL OR (length(current_content_path) BETWEEN 1 AND 512 AND substr(current_content_path, 1, 1) <> '/' AND instr(current_content_path, char(92)) = 0 AND instr(current_content_path, char(0)) = 0 AND instr(current_content_path, '//') = 0 AND instr('/' || current_content_path || '/', '/./') = 0 AND instr('/' || current_content_path || '/', '/../') = 0)");

                            t.HasCheckConstraint("ck_games_deleted_fields", "(status = 'DELETED' AND deleted_by IS NOT NULL AND deleted_at IS NOT NULL) OR (status <> 'DELETED' AND deleted_by IS NULL AND deleted_at IS NULL)");

                            t.HasCheckConstraint("ck_games_id", "substr(id, 1, 5) = 'game_' AND length(id) BETWEEN 5 AND 64 AND instr(id, char(0)) = 0");

                            t.HasCheckConstraint("ck_games_manifest_json", "length(manifest_json) BETWEEN 2 AND 1048576 AND json_valid(manifest_json) = 1 AND manifest_json <> ''");

                            t.HasCheckConstraint("ck_games_name", "length(name) BETWEEN 1 AND 200 AND instr(name, char(0)) = 0");

                            t.HasCheckConstraint("ck_games_owner_id", "substr(owner_user_id, 1, 4) = 'usr_' AND length(owner_user_id) BETWEEN 5 AND 64 AND instr(owner_user_id, char(0)) = 0");

                            t.HasCheckConstraint("ck_games_runtime_config_json", "length(runtime_config_json) BETWEEN 2 AND 1048576 AND json_valid(runtime_config_json) = 1 AND runtime_config_json <> ''");

                            t.HasCheckConstraint("ck_games_state_version", "state_version >= 0 AND content_revision >= 0");

                            t.HasCheckConstraint("ck_games_status", "status IN ('ACTIVE', 'BLOCKED', 'DELETED')");

                            t.HasCheckConstraint("ck_games_time_order", "created_at >= 0 AND updated_at >= created_at");

                            t.HasCheckConstraint("ck_games_visibility", "visibility IN ('PRIVATE', 'SERVER_SHARED')");

                            t.HasCheckConstraint("ck_games_workspace", "(workspace_status = 'NONE' AND workspace_path IS NULL) OR (workspace_status <> 'NONE' AND workspace_path IS NOT NULL)");

                            t.HasCheckConstraint("ck_games_workspace_path", "workspace_path IS NULL OR (length(workspace_path) BETWEEN 1 AND 512 AND substr(workspace_path, 1, 1) <> '/' AND instr(workspace_path, char(92)) = 0 AND instr(workspace_path, char(0)) = 0 AND instr(workspace_path, '//') = 0 AND instr('/' || workspace_path || '/', '/./') = 0 AND instr('/' || workspace_path || '/', '/../') = 0)");

                            t.HasCheckConstraint("ck_games_workspace_status", "workspace_status IN ('NONE', 'DRAFT', 'VALIDATING')");
                        });
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.IdempotencyRecordRow", b =>
                {
                    b.Property<string>("ActorUserId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("Scope")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("scope");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("idempotency_key");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expires_at");

                    b.Property<string>("RequestDigest")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT")
                        .HasColumnName("request_digest");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}")
                        .HasColumnName("response_json");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("response_status");

                    b.HasKey("ActorUserId", "Scope", "IdempotencyKey")
                        .HasName("pk_idempotency_records");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_records_expires_at");

                    b.ToTable("idempotency_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_idempotency_actor_id", "substr(actor_user_id, 1, 4) = 'usr_' AND length(actor_user_id) BETWEEN 5 AND 64 AND instr(actor_user_id, char(0)) = 0");

                            t.HasCheckConstraint("ck_idempotency_key", "length(idempotency_key) BETWEEN 1 AND 256 AND instr(idempotency_key, char(0)) = 0");

                            t.HasCheckConstraint("ck_idempotency_request_digest", "length(request_digest) = 71 AND substr(request_digest, 1, 7) = 'sha256:' AND lower(request_digest) = request_digest AND substr(request_digest, 8) NOT GLOB '*[^0-9a-f]*' AND length(substr(request_digest, 8)) = 64");

                            t.HasCheckConstraint("ck_idempotency_resource_id", "resource_id IS NULL OR (length(resource_id) BETWEEN 1 AND 128 AND instr(resource_id, char(0)) = 0)");

                            t.HasCheckConstraint("ck_idempotency_response_json", "length(response_json) BETWEEN 2 AND 1048576 AND json_valid(response_json) = 1 AND response_json <> ''");

                            t.HasCheckConstraint("ck_idempotency_response_status", "response_status BETWEEN 100 AND 599");

                            t.HasCheckConstraint("ck_idempotency_scope", "length(scope) BETWEEN 1 AND 100 AND instr(scope, char(0)) = 0");

                            t.HasCheckConstraint("ck_idempotency_time_order", "created_at >= 0 AND expires_at > created_at");
                        });
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.InstanceStateRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BootstrapStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("bootstrap_status");

                    b.Property<string>("InitialAdminUserId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("initial_admin_user_id");

                    b.Property<long?>("InitializedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("initialized_at");

                    b.Property<int>("StateVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("state_version");

                    b.HasKey("Id")
                        .HasName("pk_instance_state");

                    b.HasIndex("InitialAdminUserId")
                        .HasDatabaseName("ix_instance_state_initial_admin");

                    b.ToTable("instance_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_instance_state_id", "id = 1");

                            t.HasCheckConstraint("ck_instance_state_shape", "(bootstrap_status = 'BOOTSTRAP_REQUIRED' AND initialized_at IS NULL AND initial_admin_user_id IS NULL) OR (bootstrap_status = 'COMPLETED' AND initialized_at IS NOT NULL AND initial_admin_user_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_instance_state_status", "bootstrap_status IN ('BOOTSTRAP_REQUIRED', 'COMPLETED')");

                            t.HasCheckConstraint("ck_instance_state_version", "state_version >= 0");
                        });
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.QuotaProfileRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<long>("MaxActiveSessions")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_active_sessions");

                    b.Property<long>("MaxGamePackageBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_game_package_bytes");

                    b.Property<long>("MaxOutputBytesPerSecond")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_output_bytes_per_second");

                    b.Property<long>("MaxSessionBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_session_bytes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("StateVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("state_version");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_quota_profiles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_quota_profiles_name");

                    b.ToTable("quota_profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_quota_profiles_id", "substr(id, 1, 4) = 'qtp_' AND length(id) BETWEEN 5 AND 64 AND instr(id, char(0)) = 0");

                            t.HasCheckConstraint("ck_quota_profiles_limits_positive", "max_active_sessions > 0 AND max_game_package_bytes > 0 AND max_session_bytes > 0 AND max_output_bytes_per_second > 0");

                            t.HasCheckConstraint("ck_quota_profiles_name", "length(name) BETWEEN 1 AND 200 AND instr(name, char(0)) = 0");

                            t.HasCheckConstraint("ck_quota_profiles_state_version", "state_version >= 0");

                            t.HasCheckConstraint("ck_quota_profiles_time_order", "created_at >= 0 AND updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.SessionRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CloseReason")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("close_reason");

                    b.Property<long?>("ClosedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("closed_at");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentPromptId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("current_prompt_id");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("game_id");

                    b.Property<long>("LastActivityAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_activity_at");

                    b.Property<long>("LastOutputSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("last_output_sequence");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("RuntimeManifestJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}")
                        .HasColumnName("runtime_manifest_json");

                    b.Property<string>("RuntimeVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("runtime_version");

                    b.Property<string>("SessionRootPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_root_path");

                    b.Property<string>("SourceContentDigest")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_content_digest");

                    b.Property<long>("SourceContentRevision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_content_revision");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<int>("StateVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("state_version");

                    b.Property<bool>("WaitingForInput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("waiting_for_input");

                    b.Property<long>("WorkerEpoch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("worker_epoch");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasAlternateKey("Id", "WorkerEpoch")
                        .HasName("ak_sessions_id_worker_epoch");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_sessions_game");

                    b.HasIndex("GameId", "SourceContentDigest")
                        .HasDatabaseName("ix_sessions_game_content_digest");

                    b.HasIndex("OwnerUserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_sessions_owner_created");

                    b.HasIndex("State", "LastActivityAt")
                        .HasDatabaseName("ix_sessions_state_activity");

                    b.ToTable("sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_sessions_close_reason", "close_reason IS NULL OR (length(close_reason) BETWEEN 1 AND 256 AND instr(close_reason, char(0)) = 0)");

                            t.HasCheckConstraint("ck_sessions_closed_fields", "(state = 'CLOSED' AND closed_at IS NOT NULL) OR (state <> 'CLOSED' AND closed_at IS NULL)");

                            t.HasCheckConstraint("ck_sessions_counters", "state_version >= 0 AND worker_epoch >= 0 AND last_output_sequence >= 0");

                            t.HasCheckConstraint("ck_sessions_game_id", "substr(game_id, 1, 5) = 'game_' AND length(game_id) BETWEEN 5 AND 64 AND instr(game_id, char(0)) = 0");

                            t.HasCheckConstraint("ck_sessions_id", "substr(id, 1, 5) = 'sess_' AND length(id) BETWEEN 5 AND 64 AND instr(id, char(0)) = 0");

                            t.HasCheckConstraint("ck_sessions_name", "length(name) BETWEEN 1 AND 200 AND instr(name, char(0)) = 0");

                            t.HasCheckConstraint("ck_sessions_owner_id", "substr(owner_user_id, 1, 4) = 'usr_' AND length(owner_user_id) BETWEEN 5 AND 64 AND instr(owner_user_id, char(0)) = 0");

                            t.HasCheckConstraint("ck_sessions_root_path", "length(session_root_path) BETWEEN 1 AND 512 AND substr(session_root_path, 1, 1) <> '/' AND instr(session_root_path, char(92)) = 0 AND instr(session_root_path, char(0)) = 0 AND instr(session_root_path, '//') = 0 AND instr('/' || session_root_path || '/', '/./') = 0 AND instr('/' || session_root_path || '/', '/../') = 0");

                            t.HasCheckConstraint("ck_sessions_runtime_manifest_json", "length(runtime_manifest_json) BETWEEN 2 AND 1048576 AND json_valid(runtime_manifest_json) = 1 AND runtime_manifest_json <> ''");

                            t.HasCheckConstraint("ck_sessions_runtime_version", "length(runtime_version) BETWEEN 1 AND 128 AND instr(runtime_version, char(0)) = 0");

                            t.HasCheckConstraint("ck_sessions_source_digest", "length(source_content_digest) = 71 AND substr(source_content_digest, 1, 7) = 'sha256:' AND lower(source_content_digest) = source_content_digest AND substr(source_content_digest, 8) NOT GLOB '*[^0-9a-f]*' AND length(substr(source_content_digest, 8)) = 64");

                            t.HasCheckConstraint("ck_sessions_source_revision", "source_content_revision > 0");

                            t.HasCheckConstraint("ck_sessions_state", "state IN ('CREATING', 'STARTING', 'RUNNING', 'DETACHED', 'STOPPING', 'CLOSED', 'CRASHED')");

                            t.HasCheckConstraint("ck_sessions_time_order", "created_at >= 0 AND last_activity_at >= created_at AND (started_at IS NULL OR started_at >= created_at) AND (closed_at IS NULL OR closed_at >= created_at)");

                            t.HasCheckConstraint("ck_sessions_waiting_prompt", "waiting_for_input IN (0, 1) AND ((waiting_for_input = 1 AND current_prompt_id IS NOT NULL AND length(current_prompt_id) BETWEEN 1 AND 256) OR (waiting_for_input = 0 AND current_prompt_id IS NULL))");
                        });
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.WorkerLeaseRow", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<long>("AcquiredAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("acquired_at");

                    b.Property<long>("Epoch")
                        .HasColumnType("INTEGER")
                        .HasColumnName("epoch");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expires_at");

                    b.Property<long>("HeartbeatAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("heartbeat_at");

                    b.Property<string>("IpcEndpoint")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("ipc_endpoint");

                    b.Property<long?>("Pid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pid");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("protocol_version");

                    b.Property<string>("RuntimeVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("runtime_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("worker_id");

                    b.HasKey("SessionId")
                        .HasName("pk_worker_leases");

                    b.HasIndex("WorkerId")
                        .IsUnique()
                        .HasDatabaseName("ux_worker_leases_worker_id");

                    b.HasIndex("SessionId", "Epoch")
                        .IsUnique()
                        .HasDatabaseName("ux_worker_leases_session_epoch");

                    b.ToTable("worker_leases", null, t =>
                        {
                            t.HasCheckConstraint("ck_worker_leases_epoch", "epoch > 0");

                            t.HasCheckConstraint("ck_worker_leases_ipc_endpoint", "length(ipc_endpoint) BETWEEN 1 AND 512 AND substr(ipc_endpoint, 1, 1) <> '/' AND instr(ipc_endpoint, char(92)) = 0 AND instr(ipc_endpoint, char(0)) = 0 AND instr(ipc_endpoint, '://') = 0 AND instr(ipc_endpoint, '//') = 0");

                            t.HasCheckConstraint("ck_worker_leases_pid", "pid IS NULL OR pid > 0");

                            t.HasCheckConstraint("ck_worker_leases_protocol_version", "protocol_version > 0");

                            t.HasCheckConstraint("ck_worker_leases_runtime_version", "length(runtime_version) BETWEEN 1 AND 128 AND instr(runtime_version, char(0)) = 0");

                            t.HasCheckConstraint("ck_worker_leases_session_id", "substr(session_id, 1, 5) = 'sess_' AND length(session_id) BETWEEN 5 AND 64 AND instr(session_id, char(0)) = 0");

                            t.HasCheckConstraint("ck_worker_leases_status", "status IN ('STARTING', 'ACTIVE', 'STOPPING', 'EXPIRED')");

                            t.HasCheckConstraint("ck_worker_leases_time_order", "acquired_at >= 0 AND heartbeat_at >= acquired_at AND expires_at > heartbeat_at");

                            t.HasCheckConstraint("ck_worker_leases_worker_id", "substr(worker_id, 1, 4) = 'wrk_' AND length(worker_id) BETWEEN 5 AND 128 AND instr(worker_id, char(0)) = 0");
                        });
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.AuthSessionRow", b =>
                {
                    b.HasOne("CloudEmuera.Infrastructure.Persistence.CloudEmueraUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auth_sessions_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.CloudEmueraUser", b =>
                {
                    b.HasOne("CloudEmuera.Infrastructure.Persistence.QuotaProfileRow", "QuotaProfile")
                        .WithMany("Users")
                        .HasForeignKey("QuotaProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_quota_profiles");

                    b.Navigation("QuotaProfile");
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.CompatibilityDiagnosticRow", b =>
                {
                    b.HasOne("CloudEmuera.Infrastructure.Persistence.GameRow", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_compatibility_diagnostics_game");

                    b.HasOne("CloudEmuera.Infrastructure.Persistence.CloudEmueraUser", null)
                        .WithMany()
                        .HasForeignKey("OverriddenBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_compatibility_diagnostics_overridden_by");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.GameContentCopyLeaseRow", b =>
                {
                    b.HasOne("CloudEmuera.Infrastructure.Persistence.GameRow", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_game_content_copy_leases_game");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.GameContentOperationRow", b =>
                {
                    b.HasOne("CloudEmuera.Infrastructure.Persistence.GameRow", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_game_content_operations_game");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.GameFileRow", b =>
                {
                    b.HasOne("CloudEmuera.Infrastructure.Persistence.GameRow", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_game_files_game");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.GamePackageIngestionRow", b =>
                {
                    b.HasOne("CloudEmuera.Infrastructure.Persistence.CloudEmueraUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_game_package_ingestions_owner");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.GameRow", b =>
                {
                    b.HasOne("CloudEmuera.Infrastructure.Persistence.CloudEmueraUser", null)
                        .WithMany()
                        .HasForeignKey("ActivatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_games_activated_by");

                    b.HasOne("CloudEmuera.Infrastructure.Persistence.CloudEmueraUser", null)
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_games_deleted_by");

                    b.HasOne("CloudEmuera.Infrastructure.Persistence.CloudEmueraUser", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_games_owner_user");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.IdempotencyRecordRow", b =>
                {
                    b.HasOne("CloudEmuera.Infrastructure.Persistence.CloudEmueraUser", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_idempotency_records_actor_user");

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.InstanceStateRow", b =>
                {
                    b.HasOne("CloudEmuera.Infrastructure.Persistence.CloudEmueraUser", null)
                        .WithMany()
                        .HasForeignKey("InitialAdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_instance_state_initial_admin");
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.SessionRow", b =>
                {
                    b.HasOne("CloudEmuera.Infrastructure.Persistence.GameRow", "Game")
                        .WithMany("Sessions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_game");

                    b.HasOne("CloudEmuera.Infrastructure.Persistence.CloudEmueraUser", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_owner_user");

                    b.Navigation("Game");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.WorkerLeaseRow", b =>
                {
                    b.HasOne("CloudEmuera.Infrastructure.Persistence.SessionRow", "Session")
                        .WithOne("WorkerLease")
                        .HasForeignKey("CloudEmuera.Infrastructure.Persistence.WorkerLeaseRow", "SessionId", "Epoch")
                        .HasPrincipalKey("CloudEmuera.Infrastructure.Persistence.SessionRow", "Id", "WorkerEpoch")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_worker_leases_session_epoch");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.GameRow", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.QuotaProfileRow", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CloudEmuera.Infrastructure.Persistence.SessionRow", b =>
                {
                    b.Navigation("WorkerLease");
                });
#pragma warning restore 612, 618
        }
    }
}
