<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../CloudEmuera.Ipc/CloudEmuera.Ipc.csproj" />
    <ProjectReference Include="../CloudEmuera.EmueraRuntime/CloudEmuera.EmueraRuntime.csproj" />
    <ProjectReference Include="../CloudEmuera.RuntimeAdapter/CloudEmuera.RuntimeAdapter.csproj" />
  </ItemGroup>
</Project>
